---
title: "Class Size"
author: "David Kane"
format: html
execute: 
  echo: false
---

```{r}
#| label: setup
#| message: false

library(tidyverse)
library(brms)
library(tidybayes)

raw_df <- read_csv("data/STAR.csv", show_col_types = FALSE)
```


```{r}

# Assume your data frame is named x
# Recode 'classtype' variable into a factor with informative labels

x <- raw_df |> 
  mutate(kinder = recode(classtype,
                         `1` = "small",
                         `2` = "regular",
                         `3` = "regular with aid")) |> 
  mutate(race = recode(race,
                       `1` = "white",
                       `2` = "black",
                       `3` = "hispanic",
                       `4` = "hispanic",
                       `5` = "others",
                       `6` = "others")) |> 
  filter(kinder %in% c("small", "regular")) |> 
  select(g4math, kinder) |> 
  drop_na()  
```


```{r}
#| cache: true
fit_cs <- brm(formula = g4math ~ kinder,
             data = x,
             family = gaussian(),
             silent = 2,
             refresh = 0,
             seed = 9)

```



```{r}
fit_cs
```

